version: '3'
services:
  openalpr:
    container_name: alpr_nodejs
    build: .
    volumes:
      - openalpr:/etc/openalpr
      - ./:/code
    ports:
      - "9091:9091"
volumes:
  openalpr:        
