version: '3'
services:
  openalpr:
    container_name: alpr_nodejs
    restart: always
    build: .
    ports:
      - "9091:9091"
    volumes:
      - openalpr:/etc/openalpr
      - ./:/code
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - dbdata:/data/db
    ports:
      - '27017:27017'
  mongo-express:
    image: mongo-express
    depends_on:
       - mongo
    ports:
       - "8081:8081"        
volumes:
  dbdata:
  openalpr:    
