version: '3'
services:
  openalpr:
    container_name: alpr_nodejs
    restart: always
    build: .
    ports:
      - '27017:27017'
      - "9091:9091"
    volumes:
      - openalpr:/etc/openalpr
      - ./:/code
      - dbdata:/data/db
volumes:
  dbdata:
  openalpr:    
