version: '3'
services:
  openalpr:
    container_name: alpr_nodejs
    restart: always
    build: .
    ports:
      - '27017:27017'
      - "9091:9091"
    volumes:
      - openalpr:/etc/openalpr
      - ./:/code
      - dbdata:/data/db
  mongo-express:
    image: mongo-express
    depends_on:
       - openalpr
    ports:
       - "8081:8081"        
volumes:
  dbdata:
  openalpr:    
